name: CI

on:
  push:
    branches: [main, deploy]
  pull_request:
    branches: [main]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 6

      - name: Set node version to 16.x
        uses: actions/setup-node@v2
        with:
          node-version: 16.x
          registry-url: https://registry.npmjs.org/
          cache: 'pnpm'

      - name: Install deps
        run: pnpm install

      - name: Build application
        run: pnpm run build && sed -i -e s,{{RELEASE_ID}},$(date +%d/%m/%Y),g dist/help/fr/content.* dist/assets/index*.js

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v2.3.1
        with:
          name: mj-scoreboard
          path: ./dist

  deploy:
    needs: build
    if: ${{ github.ref_name == 'deploy' }}
    runs-on: ubuntu-latest
    steps:
      - name: Download a Build Artifact
        uses: actions/download-artifact@v2
        with:
          name: mj-scoreboard

      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          name: id_github-actions
          known_hosts: placeholder
          config: |
            Host github.com 
            HostName ssh.github.com 
            User git
            port 443
            IdentityFile ~/.ssh/id_github-actions

      - name: Adding Known Hosts
        run: ssh-keyscan -H ssh.github.com > ~/.ssh/known_hosts

      - name: Send to gh-pages
        run: |
          git init
          git config user.name "Anh-Vu Tran"
          git config user.email "anhvutran1@gmail.com"
          git branch -m main
          git add -A
          git commit -m 'deploy'
          git push -f git@github.com:anhvut/mj-scoreboard.git main:gh-pages
